config/routes.rb
Rails.application.routes.draw do
  root 'patients#dashboard'
  resources :patients, only: [:create]
  get 'next_token', to: 'patients#next_token'
  get 'current_token', to: 'patients#current_token'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :name, presence: true
  validates_format_of :phone, presence: true, :with =>  /\d{10}/, :allow_nil => false, :allow_blank => false, :message => "Only positive number without spaces are allowed"
  validates :token, presence: true, uniqueness: true
  # validates :is_current_token

  scope :current_token, -> { where(:is_current_token => true) }

  def self.change_token_to(patient_id)
    Patient.current_token.update({:is_current_token => false})
    Patient.where("id = ?",patient_id).update({:is_current_token => true})
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
 
  attr_accessor :curr_token
  before_action :current_token, only: [:next_token]

  def dashboard
    @patients = Patient.order(:token)
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.token = generate_token

    if @patient.save
      session[:current_token] = @patient.token if curr_token.nil?
      redirect_to root_path, notice: 'Patient was successfully added.'
    else
      @patients = Patient.order(:token)
      render :dashboard
    end
  end

  def next_token
    next_patient = Patient.where('token > ?', @curr_token).order(:token).first 

    if next_patient
      
    end
    ActionCable.server.broadcast("patient_queue_channel", { token: @curr_token })

    redirect_to root_path, notice: 'Current token: #{@curr_token}'
  end

  def current_token
    current_patient = Patient.current_token.first #|| (Patient.find_by(token: @curr_token) unless @curr_token.nil?)
    puts ">>>>>>>>>>>>>>check:#{current_patient.try(:id)}"
    @curr_token = current_patient.try(:token)
  end

  private

  def patient_params
    params.permit(:name, :phone)
  end

  def generate_token
    last_patient = Patient.order(token: :desc).first
    if last_patient
      last_token = last_patient.token.match(/T-(\d+)/)[1].to_i
      new_token = "T-#{format('%03d', last_token + 1)}"
    else
      new_token = 'T-101'
    end
    new_token
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorCSM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/current_token.html.erb
<h2>Current Token</h2>
<p id="current-token"><%= @curr_token ? @curr_token : 'No current token' %></p>

app/views/patients/dashboard.html.erb
<h1>Patient Token Dashboard</h1>

<%= form_with(model: @patient, url: patients_path) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, :placeholder => "Your phone number" %>
  </div>

  <div class="actions">
    <%= form.submit 'Generate token for the patient' %>
  </div>
<% end %>

<h2>Patients</h2>
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= "#{patient.token} : #{patient.name} : (#{patient.phone})" %>
    </li>
  <% end %>
</ul>



<%= link_to 'Next Token', next_token_path, method: :post %>